name: pytest

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov torch torchaudio pytorch-lightning omegaconf

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Run Pytest
        run: |
          pytest tests/
